# Generated by Django 5.1.5 on 2025-01-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='id_sta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='name_sta',
            field=models.CharField(default='fluffy', max_length=64),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='pressure_trend',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
