# Generated by Django 5.1.5 on 2025-01-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_dashboard', '0002_weatherdata_id_sta_weatherdata_name_sta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='id_sta',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='name_sta',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='station_name',
            field=models.CharField(default='fluffy', max_length=64, null=True),
        ),
    ]
