# Generated by Django 5.1.5 on 2025-01-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_dashboard', '0003_remove_weatherdata_id_sta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='feels_like',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_chill',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_direction',
            field=models.IntegerField(default=0),
        ),
    ]
