# Generated by Django 5.1.5 on 2025-01-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_dashboard', '0004_weatherdata_feels_like_weatherdata_wind_chill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='heat_index',
            field=models.FloatField(default=0),
        ),
    ]
