# Generated by Django 5.1.5 on 2025-01-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_dashboard', '0005_weatherdata_heat_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='sea_level_pressure',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_gust',
            field=models.FloatField(default=0),
        ),
    ]
