# Generated by Django 5.1.5 on 2025-02-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_dashboard', '0006_weatherdata_sea_level_pressure_weatherdata_wind_gust'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='dew_point',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
