# Generated by Django 5.1.5 on 2025-02-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_dashboard', '0007_weatherdata_dew_point_alter_weatherdata_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='lastsample',
            field=models.FloatField(default=0),
        ),
    ]
